name: Celestial Mind
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      twitter_username: "garuda_4244"
      ga_id: "Your google analytics id"
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      importance: 5
      layout: post
      
